application: fortune-teller
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /my_blog\.css
  static_files: my_blog.css
  upload: my_blog\.css

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

#static directories should go ABOVE the catch all url (.*)
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
#add jinja2 here, remember in .yaml files, every white space is important
